const PRODUCT_CATALOG = [
  // ── EV TİPİ DİKİŞ MAKİNELERİ ──────────────────────────────
  {
    id: "singer-m3205",
    title: "Singer M3205 Dikiş Makinesi",
    price: 9000,
    priceText: "9.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-m3205-dikis-makinesi",
    inStock: true,
  },
  {
    id: "singer-simple-3223g",
    title: "Singer Simple 3223G Dikiş Makinesi",
    price: 7400,
    priceText: "7.400 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-simple-3223g-dikis-makinesi",
    inStock: true,
  },
  {
    id: "singer-simple-3223r",
    title: "Singer Simple 3223R Dikiş Makinesi",
    price: 7400,
    priceText: "7.400 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-simple-3223r-dikis-makinesi",
    inStock: true,
  },
  {
    id: "singer-hd500",
    title: "Singer HD500 Classic Gold Dikiş Makinesi",
    price: 14000,
    priceText: "14.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-hd500-classic-gold-dikis-makinesi",
    inStock: true,
  },
  {
    id: "singer-hd4432-black",
    title: "Singer Heavy Duty 4432 Black Edition Dikiş Makinesi",
    price: 14000,
    priceText: "14.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-heavy-duty-4432-black-dikis-makinasi",
    inStock: true,
  },
  {
    id: "singer-c5205",
    title: "Singer C5205-PR Dikiş Makinesi",
    price: 12000,
    priceText: "12.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-c5205-pr-dikis-makinesi",
    inStock: true,
  },
  {
    id: "singer-c5605",
    title: "Singer C5605 Elektronik Dikiş Makinesi",
    price: 14000,
    priceText: "14.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-c5605-elektronik-dikis-makinasi",
    inStock: true,
  },
  {
    id: "singer-c5655",
    title: "Singer C5655 Elektronik Piko Makinası",
    price: 14000,
    priceText: "14.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-c5655-elektronik-piko-makinasi",
    inStock: true,
  },
  {
    id: "singer-elite-ce677",
    title: "Singer Elite CE677 Dikiş Makinesi",
    price: 20000,
    priceText: "20.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-elite-ce677-dikis-makinasi",
    inStock: true,
  },
  {
    id: "singer-se9185",
    title: "Singer Nakış ve Dikiş Makinesi SE9185",
    price: 65000,
    priceText: "65.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-dikis-ve-nakis-se9185-makinesi",
    inStock: true,
  },
  {
    id: "singer-brilliance-6180",
    title: "Singer Brilliance Dikiş Makinası 6180",
    price: 12217,
    priceText: "12.217 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/singer-brilliance-dikis-makinasi-6180",
    inStock: true,
  },
  {
    id: "pfaff-smarter-140s",
    title: "Pfaff Smarter 140S Dikiş Makinesi",
    price: 12000,
    priceText: "12.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/pfaff-smarter-140s-dikis-makinesi",
    inStock: true,
  },
  {
    id: "pfaff-smarter-260c",
    title: "Pfaff Smarter 260C Dikiş Makinesi",
    price: 25000,
    priceText: "25.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/pfaff-smarter-260c-dikis-makinesi",
    inStock: true,
  },
  {
    id: "pfaff-passport-3",
    title: "Pfaff Passport 3.0 Elektronik Dikiş Makinesi",
    price: 30500,
    priceText: "30.500 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/pfaff-passport-3-0-elektronik-dikis-makinesi",
    inStock: true,
  },
  {
    id: "pfaff-performance-icon",
    title: "Pfaff Performance Icon Dikiş Makinesi",
    price: 220000,
    priceText: "220.000 TL",
    category: "ev_tipi",
    machineType: "ev_tipi",
    url: "https://www.irfmak.com/urun/pfaff-creative-icon-dikis-makinesi",
    inStock: true,
  },

  // ── SANAYİ DÜZ DİKİŞ ───────────────────────────────────────
  {
    id: "singer-142g-cea",
    title: "Singer 142G E Serisi Düz Dikiş Kilit Makinası",
    price: 20000,
    priceText: "20.000 TL",
    category: "sanayi_duz_dikis",
    machineType: "duz_dikis",
    url: "https://www.irfmak.com/urun/singer-142g-30cea-16-155-e-serisi-duz-dikis-kilit-makinasi",
    inStock: true,
  },
  {
    id: "singer-142g-cfa",
    title: "Singer 142G E Serisi Düz Dikiş Kilit Makinası (CFA)",
    price: 18000,
    priceText: "18.000 TL",
    category: "sanayi_duz_dikis",
    machineType: "duz_dikis",
    url: "https://www.irfmak.com/urun/singer-142g-30cfa-16-155-e-serisi-duz-dikis-kilit-makinasi",
    inStock: false,
  },

  // ── OVERLOK ─────────────────────────────────────────────────
  {
    id: "singer-elite-se017",
    title: "Singer Elite SE017 Overlok Makinesi",
    price: 15000,
    priceText: "15.000 TL",
    category: "ev_overlok",
    machineType: "overlok",
    url: "https://www.irfmak.com/urun/singer-elite-se017-overlok-makinesi",
    inStock: true,
  },
  {
    id: "singer-324g-overlok",
    title: "Singer 324G 5 İplik Overlok Makinası",
    price: 23000,
    priceText: "23.000 TL",
    category: "sanayi_overlok",
    machineType: "overlok",
    url: "https://www.irfmak.com/urun/singer-324g-251m55ea06155-5-iplik-overlok-makinasi",
    inStock: false,
  },

  // ── ÜTÜ ─────────────────────────────────────────────────────
  {
    id: "singer-swc02e",
    title: "Singer SWC.02E Steam Works Askıda Buhar Kazanlı Ütü",
    price: 6000,
    priceText: "6.000 TL",
    category: "utu",
    machineType: "utu",
    url: "https://www.irfmak.com/urun/singer-swc-02e-steam-works-classic-askida-buhar-kazanli-utu-1",
    inStock: true,
  },

  // ── YEDEK PARÇA / İĞNE ──────────────────────────────────────
  {
    id: "singer-igne",
    title: "Singer İğne Çeşitleri",
    price: null,
    priceText: "Çeşitli fiyatlar",
    category: "yedek_parca",
    machineType: "igne",
    url: "https://www.irfmak.com/kategori/singer-igne-cesitleri",
    inStock: true,
  },
  {
    id: "pfaff-igne",
    title: "Pfaff İğne Çeşitleri",
    price: null,
    priceText: "Çeşitli fiyatlar",
    category: "yedek_parca",
    machineType: "igne",
    url: "https://www.irfmak.com/kategori/pfaff-igne-cesitleri",
    inStock: true,
  },
  {
    id: "ev-tipi-ayak",
    title: "Ev Tipi Makine Ayak Çeşitleri",
    price: null,
    priceText: "Çeşitli fiyatlar",
    category: "yedek_parca",
    machineType: "parca",
    url: "https://www.irfmak.com/kategori/ev-tipi-makine-ayaklari",
    inStock: true,
  },
  {
    id: "sanayi-tipi-ayak",
    title: "Sanayi Tipi Makine Ayak Çeşitleri",
    price: null,
    priceText: "Çeşitli fiyatlar",
    category: "yedek_parca",
    machineType: "parca",
    url: "https://www.irfmak.com/kategori/sanayi-tipi-ayak-cesitleri",
    inStock: true,
  },
];

module.exports = { PRODUCT_CATALOG };